#pragma config(Sensor, dgtl1,  frontFlipLeds,  sensorLEDtoVCC)
#pragma config(Sensor, dgtl2,  backFlipLeds,   sensorLEDtoVCC)
#pragma config(Sensor, dgtl3,  tankLeds,       sensorLEDtoVCC)
#pragma config(Motor,  port2,           rDrive,       tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           brLift,       tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           mrLift,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           trLift,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           tlLift,        tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           mlLift,        tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           blDrive,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           lDrive,       tmotorVex393HighSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!



#define RX 0
#define RY 1
#define LY 2
#define LX 3

#define LIFT_UP_BTN (vexRT[Btn5U])
#define LIFT_DWN_BTN (vexRT[Btn5D])
//#define LIFT_UP_SLOW_BTN (vexRT[Btn6U])
//#define LIFT_DWN_SLOW_BTN (vexRT[Btn6D])

#define FLIP_DRIVE_BTN (vexRT[Btn8L])
#define TANK_BTN (vexRT[Btn8R])

#define HOLD_PWR_UP_BTN (vexRT[Btn8U])
#define HOLD_PWR_DWN_BTN (vexRT[Btn8D])
#define HOLD_PWR_RESET_BTN (vexRT[Btn7D])

#define setRDrive(pwr) motor[rDrive] = pwr
#define setLDrive(pwr) motor[lDrive] = pwr

#define setLift(pwr) \
	motor[blLift] = \
		motor[mlLift] = \
		motor[tlLift] = \
		motor[trLift] = \
		motor[mrLift] = \
		motor[brLift] = \
		pwr

bool upLeds(tSensors led, bool val) {
	SensorValue[led] = val;
	return val;
}

typedef struct {
	bool out;
	word valLast;

} Toggle;

bool upToggle(Toggle* toggle, word in) {
	if(in != toggle->valLast)
		toggle->out = true;
	else
		toggle->out = false;
	toggle->valLast = in;
	return toggle->out;
}

bool pressToggle(Toggle* toggle, word in) {
	if(toggle->out && in)
		return true;
	else
		return false;
}

Toggle flipDriveToggle,
	tankToggle,
	liftPwrUpToggle,
	liftPwrDwnToggle,
	liftPwrResetToggle;

void pre_auton()
{

}

task autonomous()
{
	setRDrive(127);
	setLDrive(127);
	wait1Msec(2500);
	setRDrive(0);
	setLDrive(0);
	wait1Msec(250);
	setLift(127);
	wait1Msec(1000);
	setLift(0);
	wait1Msec(250);
	setLift(-127);
	wait1Msec(500);
	setLift(0);
}

task usercontrol() {
	int stick[4],
		liftPwr,
		rDrivePwr,
		lDrivePwr,
		tempDriveVar,
//		liftHoldPwr = 15,
		liftUpPwr = 127,
		liftDwnPwr = -63;
	const int stickThresh = 15;
		//holdPwrInc = 7;

	static bool flipDrive = false,
		tank = false;

	while(true) {
		for(int i = 0; i < 4; i++)
			stick[i] =
				(fabs(vexRT[i]) >= stickThresh)
				? vexRT[i]
				: 0;

		upToggle(&flipDriveToggle, FLIP_DRIVE_BTN);
		upToggle(&tankToggle, TANK_BTN);
		//upToggle(&liftPwrUpToggle, HOLD_PWR_UP_BTN);
		//upToggle(&liftPwrDwnToggle, HOLD_PWR_DWN_BTN);
		//upToggle(&liftPwrResetToggle, HOLD_PWR_RESET_BTN);

		if(pressToggle(&flipDriveToggle, FLIP_DRIVE_BTN))
			flipDrive = !flipDrive;
		if(pressToggle(&tankToggle, TANK_BTN))
			tank = !tank;

		//liftHoldPwr =
		//	(pressToggle(&liftPwrUpToggle, HOLD_PWR_UP_BTN)
		//		^ pressToggle(&liftPwrDwnToggle, HOLD_PWR_DWN_BTN)
		//		^ pressToggle(&liftPwrResetToggle, HOLD_PWR_RESET_BTN))
		//	? (pressToggle(&liftPwrUpToggle, HOLD_PWR_UP_BTN))
		//		? liftHoldPwr + holdPwrInc
		//		: (pressToggle(&liftPwrDwnToggle, HOLD_PWR_DWN_BTN))
		//			? liftHoldPwr - holdPwrInc
		//			: 15
		//	: liftHoldPwr;

		
			
		upLeds(frontFlipLeds, !flipDrive);
		upLeds(backFlipLeds, flipDrive);
		upLeds(tankLeds, tank);

		if(LIFT_UP_BTN
			//^ LIFT_UP_SLOW_BTN
			^ LIFT_DWN_BTN)
			//^ LIFT_DWN_SLOW_BTN)
		{
			if(LIFT_UP_BTN)
				liftPwr = liftUpPwr;
			//else if(LIFT_UP_SLOW_BTN)
			//	liftPwr = 31;
			//else if(LIFT_DWN_SLOW_BTN)
			//	liftPwr = -31;
			else
				liftPwr = liftDwnPwr;
		}
		else
				liftPwr = 23;
				
		if(tank) {
			rDrivePwr = stick[RY];
			lDrivePwr = stick[LY];
		}
		else {
			rDrivePwr = vexRT[LY] - vexRT[RX];
			lDrivePwr = vexRT[LY] + vexRT[RX];
		}

		if(flipDrive) {
			tempDriveVar = rDrivePwr;
			rDrivePwr = -lDrivePwr;
			lDrivePwr = -tempDriveVar;
		}

		setRDrive(rDrivePwr);
		setLDrive(lDrivePwr);

		setLift(liftPwr);

		wait1Msec(20);
	}
}
