#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    peBatt,         sensorAnalog)
#pragma config(Sensor, dgtl1,  hangPneu,       sensorDigitalOut)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           flDrive,       tmotorVex393HighSpeed_HBridge, openLoop, reversed, driveRight, encoderPort, I2C_1)
#pragma config(Motor,  port2,           blDrive,       tmotorVex393HighSpeed_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port3,           rClaw,         tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           brLift,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           trLift,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           tlLift,        tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           blLift,        tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           lClaw,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           brDrive,       tmotorVex393HighSpeed_MC29, openLoop, driveLeft)
#pragma config(Motor,  port10,          frDrive,       tmotorVex393HighSpeed_HBridge, openLoop, driveLeft, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"


#define setDriveR(pwr) motor[frDrive] = \
	motor[brDrive] = \
	pwr

#define setDriveL(pwr) motor[flDrive] = \
	motor[blDrive] = \
	pwr

#define setLift(pwr) motor[blLift] = \
	motor[brLift] = \
	motor[tlLift] = \
	motor[trLift] = \
	pwr

#define setClaw(pwr) motor[rClaw] = \
	motor[lClaw] = \
	pwr


void arcade(short move, short rot) {
	setDriveL(move + rot);
	setDriveR(move - rot);
}

void tank(short left, short right) {
	setDriveL(left);
	setDriveR(right);
}

typedef struct {
	bool toggle;
	word btn,
		btnLast;
} Toggle;

word upToggle(Toggle* tog, word in) {
	tog->btnLast = tog->btn;
	tog->btn = in;
	return tog->btn;
}

bool getToggle(Toggle* tog) {
	return tog->toggle;
}

bool risingEdge(Toggle* tog) {
	if(tog->btn && !tog->btnLast)
		return true;
	else
		return false;
}

//bool fallEdge(Toggle* tog) {
//	if(tog->btnLast && !tog->btn)
//		return true;
//	else
//		return false;
//}

bool flipToggle(Toggle* tog) {
	tog->toggle = !tog->toggle;
	return tog->toggle;
}

void initToggle(Toggle* tog) {
	tog->toggle = false;
	tog->btn =
		tog->btnLast =
		0;
}


Toggle TankTog;


/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...

  initToggle(&TankTog);

}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................

  // Remove this function call once you have "real" code.
  AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	const byte stickThresh = 7,
		liftConstPwr = 15,
		clawConstPwr = 0;
  short stick[4],
  	liftPwr,
  	clawPwr;

  while (true)
  {
    for(short i = 0; i < 4; i++) {
    	stick[i] = (abs(vexRT[i]) > stickThresh)
    		? vexRT[i]
    		: 0;
    }

    upToggle(&TankTog, vexRT[Btn7U]);
    if(risingEdge(&TankTog))
    	flipToggle(&TankTog);

    if(getToggle(&TankTog))
    	arcade(stick[2], stick[0]);
   	else
	    tank(stick[2], stick[1]);


	  liftPwr = (vexRT[Btn5U] ^ vexRT[Btn5D])
	  	? (vexRT[Btn5U])
	  		? 127
	  		: -127
	  	: liftConstPwr;

	  setLift(liftPwr);


	  clawPwr = (vexRT[Btn6U] ^ vexRT[Btn6D])
	  	? (vexRT[Btn6U])
	  		? 127
	  		: -127
	  	: clawConstPwr;

	  setClaw(clawPwr);

	  if(vexRT[Btn7D] && vexRT[Btn8D])
	  	SensorValue[hangPneu] = 1;
	 	else if(vexRT[Btn7L] && vexRT[Btn8R])
	 		SensorValue[hangPneu] = 0;

  }
}
